openapi3.yaml, src/DAL/convertors/recordModelConverter.ts, src/DAL/repositories/recordRepository.ts, src/common/dataModels/records.ts, src/records/controllers/recordController.ts, src/records/models/recordManager.ts, src/records/routes/recordRouter.ts, tests/integration/records/helpers/recordsRequestSender.ts, tests/integration/records/records.spec.ts, tests/unit/DAL/recordModelConverter.spec.ts
| Tests added     | ✔                                                                        | …
=> feat: added find record api

openapi3.yaml, package.json, src/DAL/migration/fullSchema.sql, src/DAL/migration/v1.0.0.sql, src/DAL/repositories/recordRepository.ts, src/records/controllers/recordController.ts, tests/integration/records/records.spec.ts, tests/mocks/DBMock.ts
=> fix: db integration

package-lock.json, package.json, src/DAL/convertors/recordModelConverter.ts, tests/integration/records/records.spec.ts, tests/unit/DAL/recordModelConverter.spec.ts
| Bug fix         | ✔                                                                     |
| Chore            | ✖ …
=> fix: fix sensor type

package-lock.json, package.json
=> fix: geojson bbox validation

src/DAL/migration/fullSchema.sql, src/DAL/migration/v1.0.0.sql
Best related fields are added:
**included_in_bests**
**discretes**
=> featL best related fields

config/custom-environment-variables.json
=> feat: fix ssl enabled config format

package-lock.json, package.json, src/DAL/convertors/recordModelConverter.ts, src/DAL/migration/fullSchema.sql, src/DAL/migration/v1.2.0.sql, tests/configurations/integration/jest.config.js, tests/configurations/unit/jest.config.js, tests/integration/records/records.spec.ts, tests/unit/DAL/recordModelConverter.spec.ts
| Bug fix         | ✖                                                                        | …
=> feat: added new raster fields

src/DAL/connectionManager.ts, tests/testContainerConfig.ts
=> fix: orm connection conflict

src/DAL/convertors/recordModelConverter.ts
=> fix: return footprints as polygon

.gitignore
| Chore            | ✔                                                                       |
=> chore: fix git ignore

config/custom-environment-variables.json, config/default.json, src/serverBuilder.ts
=> feat: added payload limit configuration

package-lock.json, package.json
=> fix: added support for negative cords in bbox

src/DAL/migration/fullSchema.sql
| Bug fix         | ✔                                                                       |
=> fix: fullschema script

src/DAL/convertors/recordModelConverter.ts
=> fix: hot fix values conversion

package-lock.json, package.json, src/DAL/convertors/recordModelConverter.ts, tests/integration/records/records.spec.ts, tests/unit/DAL/recordModelConverter.spec.ts
| Tests added     | ✔                                                                        | …
=> fix: Included in best empty string

helm/templates/route.yaml, helm/values.yaml
=> fix: route

openapi3.yaml, src/DAL/repositories/recordRepository.ts, src/records/controllers/recordController.ts, src/records/models/recordManager.ts, src/records/routes/recordRouter.ts, src/serverBuilder.ts, tests/configurations/unit/jest.config.js, tests/integration/records/helpers/recordsRequestSender.ts, tests/integration/records/records.spec.ts
=> chore: added get record versions endpoint

package-lock.json, package.json
=> fix: fix update time bug

.github/workflows/build_and_push.yaml
=> fix: git action token

.gitignore, package-lock.json, package.json, src/DAL/migration/fullSchema.sql, src/DAL/migration/v2.1.0.sql, src/index.ts
=> fix: update mc-models no updateDate param

src/DAL/migration/fullSchema.sql
=> fix: fix full schema migration file

helm/templates/_tplValues.tpl
=> fix: merge operator values

config/default.json, helm/Chart.yaml, helm/templates/_helpers.tpl, helm/templates/configmap.yaml, helm/values.yaml, src/records/models/recordManager.ts
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                    |
| Chore            | ✖ …
=> feat: tracing (MAPCO-3938)

helm/templates/configmap.yaml, helm/templates/deployment.yaml, helm/values.yaml
=> fix: db with ssl certs from secret (MAPCO-4201)

src/DAL/migration/v6.0.0.sql
=> fix: point

src/DAL/repositories/recordRepository.ts
=> fix: remove duplicate where clauses on productId and productType

.github/workflows/pull_request.yaml, openapi3.yaml, package-lock.json, package.json, src/DAL/convertors/recordModelConverter.ts, src/DAL/repositories/recordRepository.ts, src/common/dataModels/records.ts, src/records/controllers/recordController.ts, src/records/models/recordManager.ts, src/utils/zod/updateRequestSchema.ts, tests/configurations/unit/jest.config.js, tests/integration/records/records.spec.ts, tests/unit/DAL/recordModelConverter.spec.ts, tests/unit/utils/zod/updateRequestSchema.spec.ts
=> fix: updatable fields(MAPCO-5518,MAPCO-5415,MAPCO-5416)

.github/workflows/pull_request.yaml, openapi3.yaml, package-lock.json, package.json, src/DAL/convertors/recordModelConverter.ts, src/DAL/repositories/recordRepository.ts, src/common/dataModels/records.ts, src/records/controllers/recordController.ts, src/records/models/recordManager.ts, src/records/routes/recordRouter.ts, src/utils/zod/updateRequestSchema.ts, tests/integration/records/helpers/recordsRequestSender.ts, tests/integration/records/records.spec.ts, tests/unit/DAL/recordModelConverter.spec.ts, tests/unit/utils/zod/updateRequestSchema.spec.ts
| Bug fix         | ✖                                                                        |
| Tests added     | ✔                                                                        | …
=> feat: Add edit route(MAPCO-5518, MAPCO-5415,MAPCO-5416)

package-lock.json, package.json, src/utils/zod/updateRequestSchema.ts, tests/unit/DAL/recordModelConverter.spec.ts, tests/unit/utils/zod/updateRequestSchema.spec.ts
=> fix: add keywords to editable metadata fields(MAPCO-5674)

src/DAL/migration/v6.2.2.sql, src/DAL/migration/v6.2.3.sql
| Bug fix         | ✔                                                                       |
| Chore            | ✖ …
=> fix: update migration to read horizontal accuracy constraint

src/DAL/convertors/recordModelConverter.ts
=> fix: error on no metadata on update(MAPCO-6527)
